name: atlascan_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_slidable: ^3.1.2
  flutter_svg: ^2.0.16
  http: ^1.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/images/scanimage.png
    - lib/images/idcard.png
    - lib/images/passport.png
    - lib/images/driver.png
    - lib/images/drawer.png
    - lib/images/settings.png
